import { Injectable, effect, signal } from '@angular/core';

export type LanguageCode = 'en' | 'ms';

const MALAY: Record<string, string> = {
  'Dashboard': 'Papan pemuka', 'Reports': 'Laporan', 'Users': 'Pengguna', 'Households': 'Isi rumah', 'Settings': 'Tetapan',
  'Sign out': 'Log keluar', 'System admin': 'Pentadbir sistem', 'Income': 'Pendapatan', 'Expenses': 'Perbelanjaan', 'Budget': 'Bajet',
  'Bills': 'Bil', 'Installments': 'Ansuran', 'Goals': 'Matlamat', 'Calendar': 'Kalendar', 'Contacts': 'Kenalan', 'More': 'Lagi',
  'Language': 'Bahasa', 'Choose your language': 'Pilih bahasa anda', 'English': 'English', 'Bahasa Melayu': 'Bahasa Melayu',
  'Powered by CloudyTempo · © 2026 All rights reserved.': 'Dikuasakan oleh CloudyTempo · © 2026 Hak cipta terpelihara.',
  'Manage your household and workspace': 'Urus isi rumah dan ruang kerja anda', 'Household': 'Isi rumah', 'Members': 'Ahli',
  'Loading members...': 'Memuatkan ahli...', 'Could not load household members.': 'Tidak dapat memuatkan ahli isi rumah.',
  'No members found.': 'Tiada ahli ditemukan.', 'You': 'Anda', 'Owner': 'Pemilik', 'Report member': 'Laporkan ahli',
  'Transfer household ownership': 'Pindahkan pemilikan isi rumah', 'Choose a member': 'Pilih ahli', 'Transfer': 'Pindah milik',
  'Enter household': 'Masuk isi rumah', 'Create new': 'Cipta baharu', 'Create and enter': 'Cipta dan masuk',
  'Household name': 'Nama isi rumah', 'Household password': 'Kata laluan isi rumah',
  'Appearance': 'Penampilan', 'Choose a color theme': 'Pilih tema warna', 'Warm brown and green': 'Perang dan hijau hangat',
  'Blue and bright yellow': 'Biru dan kuning terang', 'Cancel': 'Batal', 'Save changes': 'Simpan perubahan',
  'Report': 'Laporan', 'Why should an admin review this member?': 'Mengapa pentadbir perlu menyemak ahli ini?',
  'Describe why you think this person does not belong in the household': 'Terangkan sebab anda berpendapat orang ini bukan ahli isi rumah',
  'Send report': 'Hantar laporan', 'Currently using': 'Sedang menggunakan',
  'No active household. Enter or create one to continue.': 'Tiada isi rumah aktif. Sertai atau cipta isi rumah untuk meneruskan.',
  'A household password is required each time you enter another household.': 'Kata laluan isi rumah diperlukan setiap kali anda menyertai isi rumah lain.',
  'Create a new household': 'Cipta isi rumah baharu',
  'Sign in to Homint': 'Log masuk ke Homint', 'Welcome back': 'Selamat kembali', 'Create your account': 'Cipta akaun anda',
  'Start tracking your money': 'Mula mengurus kewangan anda', 'Email': 'E-mel', 'Password': 'Kata laluan',
  'Sign in': 'Log masuk', 'Sign up': 'Daftar', 'Forgot password?': 'Lupa kata laluan?', 'Create an account': 'Cipta akaun',
  'Back to sign in': 'Kembali ke log masuk', 'Reset your password': 'Tetapkan semula kata laluan',
  'Reset password': 'Tetapkan semula kata laluan', 'New password': 'Kata laluan baharu', 'Confirm new password': 'Sahkan kata laluan baharu',
  'Name': 'Nama', 'Join household': 'Sertai isi rumah', 'Create household': 'Cipta isi rumah',
  'Admin sign in': 'Log masuk pentadbir', 'Separate access for Homint operations': 'Akses berasingan untuk pengurusan Homint',
  'SYSTEM ADMINISTRATION': 'PENTADBIRAN SISTEM', 'Back to Homint': 'Kembali ke Homint',
  'HOMINT OPERATIONS': 'PENGURUSAN HOMINT', 'Account growth, household activity and reports': 'Pertumbuhan akaun, aktiviti isi rumah dan laporan',
  'New entries': 'Pendaftaran baharu', 'Daily': 'Harian', 'Weekly': 'Mingguan', 'Monthly': 'Bulanan',
  'active users': 'pengguna aktif', 'active households': 'isi rumah aktif',
  'New users and households': 'Pengguna dan isi rumah baharu', 'Last 30 days': '30 hari terakhir',
  'Recent activity': 'Aktiviti terkini', 'User and household activity': 'Aktiviti pengguna dan isi rumah',
  'View all activity': 'Lihat semua aktiviti', 'Show recent': 'Tunjukkan aktiviti terkini',
  'Activity will appear as users join and leave households.': 'Aktiviti akan dipaparkan apabila pengguna menyertai atau meninggalkan isi rumah.',
  'No user reports.': 'Tiada laporan pengguna.', 'open': 'Terbuka', 'reviewing': 'Dalam semakan', 'resolved': 'Selesai', 'dismissed': 'Ditutup',
  'Review': 'Semak', 'Resolve': 'Selesaikan', 'Dismiss': 'Tutup', 'Admin note': 'Nota pentadbir',
  'Search users': 'Cari pengguna', 'Search households': 'Cari isi rumah', 'Active': 'Aktif', 'Deactivated': 'Nyahaktif',
  'Edit user': 'Edit pengguna', 'Edit household': 'Edit isi rumah', 'Deactivate': 'Nyahaktifkan', 'Activate': 'Aktifkan',
  'Owner:': 'Pemilik:', 'No active household': 'Tiada isi rumah aktif', 'active members': 'ahli aktif', 'linked': 'dipautkan',
  'Joined': 'Menyertai', 'Created': 'Dicipta', 'Save': 'Simpan', 'Delete': 'Padam', 'Search': 'Cari',
  'Malay': 'Bahasa Melayu', 'All': 'Semua', 'Status': 'Status', 'Date': 'Tarikh',
  'Account growth and household activity': 'Pertumbuhan akaun dan aktiviti isi rumah', 'Open reports': 'Laporan terbuka',
  'Refresh': 'Muat semula', 'Loading reports...': 'Memuatkan laporan...', 'No open reports.': 'Tiada laporan terbuka.',
  'Reported by': 'Dilaporkan oleh', 'Received': 'Diterima', 'Open report tracker': 'Buka penjejak laporan',
  'Signing in...': 'Sedang log masuk...', 'CASE MANAGEMENT': 'PENGURUSAN KES',
  'Review household membership concerns and track outcomes': 'Semak isu keahlian isi rumah dan jejak tindakan',
  'Report totals': 'Jumlah laporan', 'total': 'jumlah', 'Search records': 'Cari rekod',
  'ID, household, user or reason': 'ID, isi rumah, pengguna atau sebab', 'Filter report status': 'Tapis status laporan',
  'No reports match these filters.': 'Tiada laporan sepadan dengan penapis ini.',
  'No reports have been submitted.': 'Tiada laporan dihantar.', 'Record': 'Rekod', 'Reported member': 'Ahli dilaporkan',
  'Reporter': 'Pelapor', 'Concern': 'Isu', 'Open': 'Terbuka', 'Reviewing': 'Dalam semakan',
  'Resolved': 'Selesai', 'Dismissed': 'Ditutup', 'removed': 'dikeluarkan', 'Save review': 'Simpan semakan',
  'Update record': 'Kemas kini rekod', 'Reviewed by': 'Disemak oleh', 'Not reviewed': 'Belum disemak',
  'Updated': 'Dikemas kini', 'Closed': 'Ditutup', 'Resolution or follow-up': 'Penyelesaian atau tindakan susulan',
  'DIRECTORY': 'DIREKTORI', 'Manage finance accounts and access': 'Urus akaun kewangan dan akses',
  'Name, email or household': 'Nama, e-mel atau isi rumah', 'No users match.': 'Tiada pengguna sepadan.',
  'No users found.': 'Tiada pengguna ditemukan.',
  'Password reset required on next sign in': 'Kata laluan perlu ditetapkan semula semasa log masuk seterusnya',
  'Manage household status, ownership and membership': 'Urus status, pemilikan dan keahlian isi rumah',
  'Household or owner': 'Isi rumah atau pemilik', 'No households match.': 'Tiada isi rumah sepadan.',
  'No households found.': 'Tiada isi rumah ditemukan.', 'Unassigned': 'Belum ditetapkan',
  'Bills & subscriptions': 'Bil dan langganan', 'Recurring payments with no end date, and when each is next due': 'Bayaran berulang tanpa tarikh tamat dan tarikh bayaran seterusnya',
  'Add bill': 'Tambah bil', 'Monthly cost by category': 'Kos bulanan mengikut kategori', 'All bills': 'Semua bil',
  'No bills yet. Add Unifi, Netflix, insurance or road tax to get reminders.': 'Belum ada bil. Tambah Unifi, Netflix, insurans atau cukai jalan untuk menerima peringatan.',
  'Mark this cycle as paid': 'Tandakan kitaran ini sebagai dibayar', 'Paid': 'Dibayar', 'Undo last payment': 'Buat asal bayaran terakhir',
  'Mark paid': 'Tandakan dibayar', 'Undo payment': 'Buat asal bayaran', 'Split bills': 'Bahagikan bil', 'Split a bill': 'Bahagikan bil',
  'No split bills yet. Add a shared bill and track each person\'s share.': 'Belum ada bil kongsi. Tambah bil dan jejak bahagian setiap orang.',
  'Edit bill': 'Edit bil', 'Category': 'Kategori',
  'Amount (MYR)': 'Jumlah (MYR)', 'Repeats': 'Ulangan', 'Every 3 months': 'Setiap 3 bulan', 'Yearly': 'Tahunan',
  'Next due date': 'Tarikh perlu dibayar seterusnya', 'Paused': 'Dijeda', 'Cancelled': 'Dibatalkan',
  'Paid automatically (auto-debit)': 'Bayaran automatik (debit automatik)',
  'Add an expense automatically when I mark it paid': 'Tambah perbelanjaan secara automatik apabila ditandakan dibayar',
  'e.g. Unifi, Netflix, Car insurance': 'cth. Unifi, Netflix, insurans kereta', 'e.g. Internet': 'cth. Internet',
  'Set a limit per category and see how the month is going': 'Tetapkan had setiap kategori dan pantau perbelanjaan bulanan',
  'Set budget': 'Tetapkan bajet', 'Total budget': 'Jumlah bajet', 'Spent (budgeted)': 'Dibelanjakan (berbajet)', 'Left': 'Baki',
  'Safe to spend / day': 'Selamat dibelanjakan / hari', 'current month only': 'bulan semasa sahaja',
  'for the rest of the month': 'untuk baki bulan ini', 'Budget vs actual': 'Bajet berbanding sebenar',
  'Set a budget to see the comparison.': 'Tetapkan bajet untuk melihat perbandingan.', 'Spending with no budget': 'Perbelanjaan tanpa bajet',
  'Every category you spent on has a budget.': 'Semua kategori perbelanjaan mempunyai bajet.', 'this month': 'bulan ini',
  'Set limit': 'Tetapkan had', 'Categories': 'Kategori', 'No budgets for': 'Tiada bajet untuk',
  'yet. Tap “Set budget”, for example Groceries RM 600.': 'lagi. Tekan “Tetapkan bajet”, contohnya Barangan dapur RM 600.',
  'Over budget': 'Melebihi bajet', 'Almost there': 'Hampir mencapai had', 'On track': 'Mengikut perancangan',
  'used': 'digunakan', 'over': 'melebihi', 'on pace for': 'diunjurkan sebanyak',
  'Category (same name as the expense type)': 'Kategori (nama yang sama seperti jenis perbelanjaan)',
  'Monthly limit (MYR)': 'Had bulanan (MYR)', 'Applies from': 'Berkuat kuasa mulai',
  'onwards. Earlier months keep their old limit.': 'dan seterusnya. Had bulan terdahulu tidak berubah.', 'Save budget': 'Simpan bajet',
  'Your events, bill due dates and installments in one place': 'Acara, tarikh bil dan ansuran anda di satu tempat',
  'Tap the green button to call straight from your phone': 'Tekan butang hijau untuk membuat panggilan',
  'Emergency numbers': 'Nombor kecemasan', 'Add contact': 'Tambah kenalan', 'Search name or number': 'Cari nama atau nombor',
  'No contacts match.': 'Tiada kenalan sepadan.', 'No contacts yet. Add one, or start with the emergency numbers.': 'Belum ada kenalan. Tambah kenalan atau mulakan dengan nombor kecemasan.',
  'Compare what you spend month to month and year to year': 'Bandingkan perbelanjaan bulanan dan tahunan',
  'Import CSV': 'Import CSV', 'Add expense': 'Tambah perbelanjaan', 'Average per month': 'Purata sebulan', 'Biggest category': 'Kategori terbesar',
  'Unusual': 'Luar biasa', 'flagged expenses': 'perbelanjaan ditandakan', 'Unusual spending detected': 'Perbelanjaan luar biasa dikesan',
  'Monthly:': 'Bulanan:', 'vs': 'berbanding', 'Annual totals': 'Jumlah tahunan', 'by type, per month': 'mengikut jenis, setiap bulan',
  'share by type': 'bahagian mengikut jenis', 'No expense types recorded for': 'Tiada jenis perbelanjaan direkodkan untuk',
  'Records': 'Rekod', 'Filter by month': 'Tapis mengikut bulan', 'All months': 'Semua bulan',
  'No expenses here yet. Use “Add expense” or import your CSV.': 'Belum ada perbelanjaan. Gunakan “Tambah perbelanjaan” atau import fail CSV.',
  'Type': 'Jenis', 'Year': 'Tahun', 'Month': 'Bulan', 'Remarks': 'Catatan', 'Edit expense': 'Edit perbelanjaan',
  'Import expenses': 'Import perbelanjaan', 'Choose a CSV with columns Type, Amount, Month, Year, Remarks. Your Belanjawanku export works too. Rows already in the app are skipped, so importing twice is safe.': 'Pilih CSV dengan lajur Jenis, Jumlah, Bulan, Tahun dan Catatan. Eksport Belanjawanku juga boleh digunakan. Rekod sedia ada akan dilangkau.',
  'CSV file': 'Fail CSV', 'records ready to import': 'rekod sedia diimport', 'blank-amount rows ignored': 'baris tanpa jumlah diabaikan',
  'Skip months after this month': 'Langkau bulan selepas bulan ini', 'Close': 'Tutup', 'Import': 'Import', 'records': 'rekod',
  'Salary, side gigs, pension, and other money coming in': 'Gaji, kerja sampingan, pencen dan sumber pendapatan lain',
  'Copy recurring': 'Salin pendapatan berulang', 'Add income': 'Tambah pendapatan', 'income': 'pendapatan',
  'Left after expenses': 'Baki selepas perbelanjaan', 'expenses': 'perbelanjaan', 'Savings rate': 'Kadar simpanan',
  'of income kept': 'daripada pendapatan disimpan', 'Income vs expenses': 'Pendapatan berbanding perbelanjaan', 'By source': 'Mengikut sumber',
  'No income recorded for': 'Tiada pendapatan direkodkan untuk', 'Add any income source to see savings and budgets work together.': 'Tambah sumber pendapatan untuk melihat simpanan dan bajet bersama.',
  'Recurring': 'Berulang', 'Edit income': 'Edit pendapatan', 'Source': 'Sumber',
  'Recurring every month (can be copied forward)': 'Berulang setiap bulan (boleh disalin ke hadapan)',
  'Save towards what matters and keep it moving': 'Simpan untuk perkara penting dan teruskan kemajuan',
  'Add goal': 'Tambah matlamat', 'Goals that need attention': 'Matlamat yang memerlukan perhatian',
  'no progress update for': 'tiada kemas kini kemajuan selama', 'months': 'bulan', 'and': 'dan', 'target date': 'tarikh sasaran',
  'has passed': 'telah berlalu', 'Completion status': 'Status penyelesaian', 'Progress by goal (%)': 'Kemajuan mengikut matlamat (%)',
  'No goals yet. Add one to start tracking.': 'Belum ada matlamat. Tambah matlamat untuk mula menjejak kemajuan.',
  'Complete': 'Selesai', 'Ongoing': 'Sedang berjalan', 'Target': 'Sasaran', 'by': 'pada', 'Past date': 'Tarikh telah berlalu',
  'saved': 'disimpan', 'Last progress update:': 'Kemas kini kemajuan terakhir:', 'less than a month ago': 'kurang daripada sebulan lalu',
  'month(s) ago': 'bulan lalu', 'No change': 'Tiada perubahan', 'New saved total (MYR)': 'Jumlah simpanan baharu (MYR)',
  'New saved total': 'Jumlah simpanan baharu', 'Update': 'Kemas kini', 'Mark complete': 'Tandakan selesai',
  'Edit goal': 'Edit matlamat', 'Goal name': 'Nama matlamat', 'Target amount (MYR)': 'Jumlah sasaran (MYR)',
  'Saved so far (MYR)': 'Jumlah disimpan setakat ini (MYR)', 'Target date': 'Tarikh sasaran',
  'Track every monthly payment until it is cleared': 'Jejak setiap bayaran bulanan sehingga selesai',
  'Add installment': 'Tambah ansuran', 'Monthly commitment': 'Komitmen bulanan', 'Remaining to pay': 'Baki perlu dibayar',
  'Due in 30 days': 'Perlu dibayar dalam 30 hari', 'Total by type': 'Jumlah mengikut jenis', 'Due soon': 'Akan tiba',
  'Nothing due in the next 30 days.': 'Tiada bayaran dalam 30 hari akan datang.', 'payment': 'bayaran', 'of': 'daripada',
  'No installments yet. Add one to start tracking payments.': 'Belum ada ansuran. Tambah ansuran untuk mula menjejak bayaran.',
  'Completed': 'Selesai', 'month': 'bulan', 'due day': 'hari bayaran', 'Paid. Tap to undo': 'Dibayar. Tekan untuk buat asal',
  'Tap to mark as paid': 'Tekan untuk tandakan dibayar', 'Edit installment': 'Edit ansuran',
  'Monthly amount (MYR)': 'Jumlah bulanan (MYR)', 'Duration (months)': 'Tempoh (bulan)', 'Payment due day': 'Hari bayaran',
  'Start month': 'Bulan mula', 'Start year': 'Tahun mula', 'e.g. iPhone 15': 'cth. iPhone 15',
  'Prayer times': 'Waktu solat', 'Fajr': 'Subuh', 'Sunrise': 'Syuruk', 'Dhuhr': 'Zohor', 'Asr': 'Asar', 'Maghrib': 'Maghrib', 'Isha': 'Isyak',
  'Locating…': 'Mencari lokasi…', 'Kuala Lumpur (default location)': 'Kuala Lumpur (lokasi lalai)', 'Your current location': 'Lokasi semasa anda',
  'Could not load prayer times. Check your internet connection.': 'Tidak dapat memuatkan waktu solat. Semak sambungan internet anda.',
  'Today': 'Hari ini', 'Previous month': 'Bulan sebelumnya', 'Next month': 'Bulan seterusnya', 'All day': 'Sepanjang hari',
  'Edit event': 'Edit acara', 'Delete event': 'Padam acara', 'Event title': 'Tajuk acara', 'Save event': 'Simpan acara',
  'Add event': 'Tambah acara', 'Nothing on this day.': 'Tiada apa-apa pada hari ini.', 'Coming up': 'Akan datang',
  'No events or due dates in the next 60 days.': 'Tiada acara atau tarikh bayaran dalam 60 hari akan datang.',
  'Show less': 'Tunjukkan kurang', 'Show all': 'Tunjukkan semua', 'Installment': 'Ansuran', 'Bill': 'Bil',
  'Overdue': 'Tertunggak', 'Quick call': 'Panggilan pantas', 'Needs attention': 'Memerlukan perhatian',
  'Payments due (30d)': 'Bayaran perlu dibayar (30 hari)', 'unusual, over budget or stalled': 'luar biasa, melebihi bajet atau terbantut',
  'Spending': 'Perbelanjaan', 'Cashflow': 'Aliran tunai', 'Upcoming payments': 'Bayaran akan datang',
  'Monthly expenses: this year vs last': 'Perbelanjaan bulanan: tahun ini berbanding tahun lalu',
  'No expenses recorded for': 'Tiada perbelanjaan direkodkan untuk',
  'Installments by type': 'Ansuran mengikut jenis', 'Manage': 'Urus', 'Goal summary is unavailable.': 'Ringkasan matlamat tidak tersedia.',
  'Payments due in 30 days': 'Bayaran perlu dibayar dalam 30 hari',
  'Calendar & events': 'Kalendar dan acara', 'Open full': 'Buka penuh',
  'All clear. Nothing unusual right now.': 'Semua baik. Tiada perkara luar biasa sekarang.',
  'Star a contact to pin it here.': 'Tandakan kenalan sebagai kegemaran untuk memaparkannya di sini.', 'All contacts': 'Semua kenalan',
  'This month': 'Bulan ini', 'vs previous month': 'berbanding bulan sebelumnya',
  'Left after spending': 'Baki selepas perbelanjaan', 'to see this': 'untuk melihat baki ini',
};

@Injectable({ providedIn: 'root' })
export class Language {
  code = signal<LanguageCode>(localStorage.getItem('language') === 'ms' ? 'ms' : 'en');
  constructor() {
    document.documentElement.lang = this.code();
    effect(() => {
      const code = this.code();
      document.documentElement.lang = code === 'ms' ? 'ms-MY' : 'en';
      localStorage.setItem('language', code);
    });
  }
  set(code: LanguageCode) { this.code.set(code); }
  text(value: string) { this.code(); return this.code() === 'ms' ? MALAY[value] || value : value; }
}
